### ISSUE TITLE
[Linux] GLIBC version mishmash issue

### ISSUE THREAD

**Issue by mdziczkowski** [artap-framework/agrossuite#5]
### Issue Description:

While attempting to start, Agros has falied due a `GLIBC` and `GLIBCXX` version mismash, even if on my Linux are installed the latest versions of libraries with are providing them.

Please fix the issue asap. Thanks

**Comment by arnyaa** [comment]
Does not run in Kubuntu 24.04!!
[error_message.txt](https://github.com/user-attachments/files/16957944/error_message.txt)
Eagerly waiting for the issue to be resolved. 
Sorry for the trouble. 
Regards, 
aranyaa

**Comment by mdziczkowski** [comment]
I think that the best solution would be  either a complete removal of static GLIBC and GLIBCXX versions from the main app or making the app ignore them (with in my modest opinion could be simplier to do)

**Comment by mdziczkowski** [comment]
Checking the status of the issue. Please keep me updated about it

**Comment by mdziczkowski** [comment]
suspending as stale due no answer
